// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcGDUOid1HbMbKvW4Q8mOblFeEhbl_SxA',
    appId: '1:634000662238:web:0ffffced75a95045ae2c4f',
    messagingSenderId: '634000662238',
    projectId: 'qanuni-499f2',
    authDomain: 'qanuni-499f2.firebaseapp.com',
    storageBucket: 'qanuni-499f2.firebasestorage.app',
    measurementId: 'G-1YHRG2Z7N4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcGDUOid1HbMbKvW4Q8mOblFeEhbl_SxA',
    appId: '1:634000662238:web:cfacac6d0b00d208ae2c4f',
    messagingSenderId: '634000662238',
    projectId: 'qanuni-499f2',
    authDomain: 'qanuni-499f2.firebaseapp.com',
    storageBucket: 'qanuni-499f2.firebasestorage.app',
    measurementId: 'G-Q3RH8FCZSN',
  );
}
